/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as TelegramRouteImport } from './routes/telegram'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'

const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramRoute = TelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/notes': typeof NotesRoute
  '/reader': typeof ReaderRoute
  '/tasks': typeof TasksRoute
  '/telegram': typeof TelegramRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/notes': typeof NotesRoute
  '/reader': typeof ReaderRoute
  '/tasks': typeof TasksRoute
  '/telegram': typeof TelegramRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/notes': typeof NotesRoute
  '/reader': typeof ReaderRoute
  '/tasks': typeof TasksRoute
  '/telegram': typeof TelegramRoute
  '/tracker': typeof TrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/notes'
    | '/reader'
    | '/tasks'
    | '/telegram'
    | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/notes'
    | '/reader'
    | '/tasks'
    | '/telegram'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/notes'
    | '/reader'
    | '/tasks'
    | '/telegram'
    | '/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  NotesRoute: typeof NotesRoute
  ReaderRoute: typeof ReaderRoute
  TasksRoute: typeof TasksRoute
  TelegramRoute: typeof TelegramRoute
  TrackerRoute: typeof TrackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram': {
      id: '/telegram'
      path: '/telegram'
      fullPath: '/telegram'
      preLoaderRoute: typeof TelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  NotesRoute: NotesRoute,
  ReaderRoute: ReaderRoute,
  TasksRoute: TasksRoute,
  TelegramRoute: TelegramRoute,
  TrackerRoute: TrackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
